### ISSUE TITLE
Crashed with using using polishing kit.

### ISSUE THREAD

**Issue by awnc** [TheIllusiveC4/ConstructsArmory#16]
When I am using "Polishing Kit" to upgrades a chestplate,game crashed.
This is crash report:Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at c4.conarm.lib.utils.ArmorBuilder.tryModifyArmor(ArmorBuilder.java:187)
	at c4.conarm.armor.common.inventory.ContainerArmorForge.modifyArmor(ContainerArmorForge.java:223)
	at c4.conarm.armor.common.inventory.ContainerArmorForge.func_75130_a(ContainerArmorForge.java:142)
	at c4.conarm.armor.common.inventory.SlotArmorForgeIn.func_75218_e(SlotArmorForgeIn.java:32)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:71)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:195)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:587)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146286_b(GuiMultiModule.java:286)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, I can use the Polishing Kit just fine.  Which version of Construct's Armory are you using? Is this in single player or on a server? Can you reproduce this in a clean install with just Construct's Armory, Mantle, and Tinkers' Construct?

**Comment by awnc** [comment]
Thank you,I have solved this problem.

**Comment by TheIllusiveC4** [comment]
Oh ok, no problem.
