### ISSUE TITLE
Kalendrite armor causing crash

### ISSUE THREAD

**Issue by slushieboy99** [TheIllusiveC4/ConstructsArmory#164]
When equipping Kalendrite armor, my client and server crashes.

`java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at it.hurts.metallurgy_reforged.integration.mods.conarm.MetallurgyConArmorStats.isThatArmorTraitLeveled(MetallurgyConArmorStats.java:97)
    at it.hurts.metallurgy_reforged.integration.mods.conarm.traits.TraitStrongly.onArmorTick(TraitStrongly.java:30)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2086_TraitStrongly_onArmorTick_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
`

**Comment by kierajreed** [comment]
Please post a mod list with all versions. Also, attempt to recreate this with only ConArm and its dependencies.

**Comment by TheIllusiveC4** [comment]
Construct's Armory is not in the stacktrace, it's only Metallurgy 4 Reforged and their integration trait "Strongly". Please report this to those developers instead.

**Comment by slushieboy99** [comment]
I've since figured that out, thank you. For anyone else with this issue, the Metallurgy 4 devs have said that this issue should be fixed in the next update.

**Comment by Davoleo** [comment]
Sorry for the trouble :P @TheIllusiveC4
