### ISSUE TITLE
Manyullyn/Prideful causing player disconnect

### ISSUE THREAD

**Issue by MxtressMyxx** [TheIllusiveC4/ConstructsArmory#28]
```[23:11:23] [Server thread/ERROR] [FML]: 44: ASM: erebus.core.handler.AntiVenomDurationHandler@44700092 playerAntiVenomTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[23:11:23] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /142.105.192.240:51167
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_162]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_162]
        at c4.conarm.armor.traits.TraitPrideful.onAbilityTick(TraitPrideful.java:47) ~[TraitPrideful.class:?]
        at c4.conarm.armor.ArmorEvents.onPlayerTick(ArmorEvents.java:46) ~[ArmorEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1766_ArmorEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
[23:11:28] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: meoil lost connection: Disconnected
[23:11:28] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: meoil left the game```

**Comment by TheIllusiveC4** [comment]
This is a known issue, I've fixed it for the next update.
